[project]
requires-python = ">=3.9"


[tool.black]
line-length = 100
quiet = true


[tool.pytest.ini_options]
testpaths = 't/'
pythonpath = '.'


[tool.ruff]
line-length = 100

[tool.ruff.lint.isort]
force-sort-within-sections = true
lines-after-imports = 2
