#!/bin/sh

kindle_dir=/run/media/mlb/Kindle/documents/
[ -d "$kindle_dir" ] || {
  echo Kindle not mounted.
  exit 1
}

cd ~/ebooks/

# clean up cruft
~/clean.py

# copy any new files over
# FIXME nothing to do here yet

# rsync
rsync -hav --delete /run/media/mlb/Kindle/ /home/local/mlb/.kindle/ --exclude-from ~/.kindle-excludes

# recalculate wordcounts
~/wordcount/wordcount.py
./wordcounts.py

# update wordcounts and suggestions
sort -nr ~/wordcounts/article-lengths.txt | cut -c-50 > /run/media/mlb/Kindle/documents/wordcounts/wordcounts.txt
(
  ./suggestions.py wordcounts/books-lengths.txt
  echo ----
  ./suggestions.py wordcounts/short-stories-lengths.txt
) | cut -c-50 > /run/media/mlb/Kindle/documents/wordcounts/suggestions.txt

